name: adventures_in_2d_games
description: Using Flame to replicate gather.town (the 2d game part).
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  a_star_algorithm:
  flame: ^1.0.0-releasecandidate.12
  web_socket_game_server_types:
    git: https://github.com/Adventures-In/web_socket_game_server_types.git
  
  freezed_annotation:
  json_annotation:
  redfire:
    git: https://github.com/enspyrco/redfire.git
    # path: /Users/nick/git/orgs/enspyrco/redfire
  web_socket_channel:
  flutter_redux:
  fast_immutable_collections:

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  freezed:
  json_serializable:

flutter:
  assets:
    - assets/images/bald.png